# Generated by Django 3.1.4 on 2020-12-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tenure_Months', models.FloatField()),
                ('Dependents', models.CharField(max_length=130)),
                ('Internet_Service', models.CharField(max_length=130)),
                ('Online_Security', models.CharField(max_length=130)),
                ('Online_Backup', models.CharField(max_length=130)),
                ('Device_Protection', models.CharField(max_length=130)),
                ('Tech_Support', models.CharField(max_length=130)),
                ('Streaming_TV', models.CharField(max_length=130)),
                ('Streaming_Movies', models.CharField(max_length=130)),
                ('Contract', models.CharField(max_length=130)),
                ('Payment_Method', models.CharField(max_length=130)),
                ('classification', models.CharField(max_length=30)),
            ],
        ),
    ]
