# Generated by Django 3.1.4 on 2021-01-07 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='Monthly_Charges',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predresults',
            name='Paperless_Billing',
            field=models.CharField(default=django.utils.timezone.now, max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predresults',
            name='Partner',
            field=models.CharField(default='Yes', max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predresults',
            name='Senior_Citizen',
            field=models.CharField(default='Yes', max_length=130),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predresults',
            name='Tenure_Months',
            field=models.IntegerField(),
        ),
    ]
